### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by piyushbest** [Fludixx/Bedwars#2]
Server thread/CRITICAL]: ErrorException: "file_put_contents(/home/bedwars/stats.json): failed to open stream: No such file or directory" (EXCEPTION) in "src/pocketmine/utils/Config" at line 241

**Comment by piyushbest** [comment]
WAITING FOR REPLY

**Comment by Fludixx** [comment]
Can you give me your OS Name & Version?

**Comment by piyushbest** [comment]
Ok

**Comment by piyushbest** [comment]
Game version: 1.9+
Plugin-port:35701
Software: pocketmine
Version:3.6.1

**Comment by piyushbest** [comment]
Php: 7.2.0
Os: windows 8
