### ISSUE TITLE
BW 2x1 Schilder fehler

### ISSUE THREAD

**Issue by NxtUserHD** [Fludixx/Bedwars#6]
bei 2x1 runden bleibt das schild auf Full auch wenn die runde gestartet hat. Bitte behebn

**Comment by Wertzui123** [comment]
Kann er Deutsch? Also @Fludixx

**Comment by Fludixx** [comment]
oops, diden't mean to close this, is the bug still reproducible?

**Comment by Fludixx** [comment]
closing because if inactivity
