### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by piyushbest** [Fludixx/Bedwars#9]
I FIXED STATS.JSON BUT ONE PROBLEM I MAKED 50%ENGLISH HELPED A354 AND I M BUT ONE PROBLEM I DON'T KNOW HOW TO SETUP BECAUSE THIS IS ONLY 50% ENGLISH AND I DON'T KNOW ABOUT SPAWNS 10 -1 AND MORE WHAT ABOUT SPAWN -1 0 10 9 7 I NEED HELP WITH TUTORIAL

**Comment by Fludixx** [comment]
Everything should be English now
